services:
  database:
    image: postgres:16-alpine
    #build: ./database
    container_name: studportrait_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: studportrait
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - studportrait_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build: ./backend
    container_name: studportrait_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=studportrait
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      database:
        condition: service_healthy
    networks:
      - studportrait_network

  frontend:
    build: ./frontend
    container_name: studportrait_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - studportrait_network
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  studportrait_network:
    driver: bridge
