services:
  database:
    image: postgres:16-alpine
    #build: ./database
    container_name: studportrait_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: studportrait
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - studportrait_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build: ./backend
    container_name: studportrait_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=studportrait
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - LLM_SERVICE_URL=http://llm:8001
    depends_on:
      database:
        condition: service_healthy
      llm:
        service_started
    networks:
      - studportrait_network

  llm:
    build: ./llm
    container_name: studportrait_llm
    ports:
      - "8001:8001"
    volumes:
      # Монтирование папки с моделью
      - ./llm_model:/app/app/llm_model:ro
      - cache:/app/cache
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: studportrait_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - studportrait_network
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  cache:

networks:
  studportrait_network:
    driver: bridge
