# Generated by Django 5.2.7 on 2026-04-19 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceCenters',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'competencecenters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EducationLevels',
            fields=[
                ('edu_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('edu_level_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'educationlevels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('inst_id', models.AutoField(primary_key=True, serialize=False)),
                ('inst_name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'institutions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'specialties',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('rsv_id', models.CharField(max_length=512, unique=True)),
                ('student_name', models.CharField(max_length=512)),
                ('student_gender', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'studentmapping',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudyForms',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('form_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'studyforms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_rsv_id', models.CharField(max_length=512, unique=True)),
                ('part_gender', models.CharField(blank=True, max_length=16, null=True)),
                ('part_course_num', models.IntegerField(blank=True, null=True)),
                ('part_edu_level', models.ForeignKey(blank=True, db_column='part_edu_level', null=True, on_delete=django.db.models.deletion.CASCADE, to='portrait.educationlevels')),
                ('part_institution', models.ForeignKey(blank=True, db_column='part_institution', null=True, on_delete=django.db.models.deletion.CASCADE, to='portrait.institutions')),
                ('part_spec', models.ForeignKey(blank=True, db_column='part_spec', null=True, on_delete=django.db.models.deletion.CASCADE, to='portrait.specialties')),
                ('part_form', models.ForeignKey(blank=True, db_column='part_form', null=True, on_delete=django.db.models.deletion.CASCADE, to='portrait.studyforms')),
            ],
            options={
                'db_table': 'participants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_an_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_client_focus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_communication', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_leadership', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_result_orientation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_planning_org', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_rules_culture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_self_dev', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_collaboration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_stress_resistance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_emotions_communication', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_negotiations', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_digital_comm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_effective_learning', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_entrepreneurship', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_creativity_tech', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_trendwatching', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_conflict_management', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_career_management', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_burnout', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_cross_cultural_comm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_mentoring', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_participant', models.ForeignKey(db_column='course_participant', on_delete=django.db.models.deletion.CASCADE, to='portrait.participants')),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_course_num', models.IntegerField(blank=True, null=True)),
                ('res_year', models.TextField(blank=True, null=True)),
                ('res_high_potential', models.TextField(blank=True, null=True)),
                ('res_summary_report', models.TextField(blank=True, null=True)),
                ('res_comp_info_analysis', models.IntegerField(blank=True, null=True)),
                ('res_comp_planning', models.IntegerField(blank=True, null=True)),
                ('res_comp_result_orientation', models.IntegerField(blank=True, null=True)),
                ('res_comp_stress_resistance', models.IntegerField(blank=True, null=True)),
                ('res_comp_partnership', models.IntegerField(blank=True, null=True)),
                ('res_comp_rules_compliance', models.IntegerField(blank=True, null=True)),
                ('res_comp_self_development', models.IntegerField(blank=True, null=True)),
                ('res_comp_leadership', models.IntegerField(blank=True, null=True)),
                ('res_comp_emotional_intel', models.IntegerField(blank=True, null=True)),
                ('res_comp_client_focus', models.IntegerField(blank=True, null=True)),
                ('res_comp_communication', models.IntegerField(blank=True, null=True)),
                ('res_comp_passive_vocab', models.IntegerField(blank=True, null=True)),
                ('res_mot_autonomy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_altruism', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_challenge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_career', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_center', models.ForeignKey(blank=True, db_column='res_center', null=True, on_delete=django.db.models.deletion.CASCADE, to='portrait.competencecenters')),
                ('res_edu_level', models.ForeignKey(blank=True, db_column='res_edu_level', null=True, on_delete=django.db.models.deletion.CASCADE, to='portrait.educationlevels')),
                ('res_institution', models.ForeignKey(blank=True, db_column='res_institution', null=True, on_delete=django.db.models.deletion.CASCADE, to='portrait.institutions')),
                ('res_participant', models.ForeignKey(db_column='res_participant', on_delete=django.db.models.deletion.CASCADE, to='portrait.participants')),
                ('res_spec', models.ForeignKey(blank=True, db_column='res_spec', null=True, on_delete=django.db.models.deletion.CASCADE, to='portrait.specialties')),
                ('res_form', models.ForeignKey(blank=True, db_column='res_form', null=True, on_delete=django.db.models.deletion.CASCADE, to='portrait.studyforms')),
            ],
        ),
    ]
