# Generated by Django 5.2.7 on 2025-10-12 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_year', models.IntegerField()),
                ('res_uni_communication', models.IntegerField(blank=True, null=True)),
                ('res_uni_complex_thinking', models.IntegerField(blank=True, null=True)),
                ('res_uni_command_work', models.IntegerField(blank=True, null=True)),
                ('res_uni_methodicalness', models.IntegerField(blank=True, null=True)),
                ('res_uni_stress_susceptib', models.IntegerField(blank=True, null=True)),
                ('res_uni_ambitousness', models.IntegerField(blank=True, null=True)),
                ('res_uni_rules_compliance', models.IntegerField(blank=True, null=True)),
                ('res_mot_purpose', models.IntegerField(blank=True, null=True)),
                ('res_mot_cooperation', models.IntegerField(blank=True, null=True)),
                ('res_mot_creativity', models.IntegerField(blank=True, null=True)),
                ('res_mot_challenge', models.IntegerField(blank=True, null=True)),
                ('res_mot_autonomy', models.IntegerField(blank=True, null=True)),
                ('res_mot_self_development', models.IntegerField(blank=True, null=True)),
                ('res_mot_recognition', models.IntegerField(blank=True, null=True)),
                ('res_mot_career', models.IntegerField(blank=True, null=True)),
                ('res_mot_management', models.IntegerField(blank=True, null=True)),
                ('res_mot_altruism', models.IntegerField(blank=True, null=True)),
                ('res_mot_relationships', models.IntegerField(blank=True, null=True)),
                ('res_mot_affiliation', models.IntegerField(blank=True, null=True)),
                ('res_mot_tradition', models.IntegerField(blank=True, null=True)),
                ('res_mot_health', models.IntegerField(blank=True, null=True)),
                ('res_mot_stability', models.IntegerField(blank=True, null=True)),
                ('res_mot_salary', models.IntegerField(blank=True, null=True)),
                ('res_comp_digital_analysis', models.IntegerField(blank=True, null=True)),
                ('res_comp_verbal_analysis', models.IntegerField(blank=True, null=True)),
                ('res_vita_positive_self_attit', models.IntegerField(blank=True, null=True)),
                ('res_vita_attit_twrd_future', models.IntegerField(blank=True, null=True)),
                ('res_vita_organization', models.IntegerField(blank=True, null=True)),
                ('res_vita_persistence', models.IntegerField(blank=True, null=True)),
                ('res_lead_awareness', models.IntegerField(blank=True, null=True)),
                ('res_lead_proactivity', models.IntegerField(blank=True, null=True)),
                ('res_lead_command_work', models.IntegerField(blank=True, null=True)),
                ('res_lead_control', models.IntegerField(blank=True, null=True)),
                ('res_lead_social_responsib', models.IntegerField(blank=True, null=True)),
                ('res_prof_information_analysis', models.IntegerField(blank=True, null=True)),
                ('res_prof_result_orientation', models.IntegerField(blank=True, null=True)),
                ('res_prof_planning', models.IntegerField(blank=True, null=True)),
                ('res_prof_stress_resistance', models.IntegerField(blank=True, null=True)),
                ('res_prof_partnership', models.IntegerField(blank=True, null=True)),
                ('res_prof_rules_compliance', models.IntegerField(blank=True, null=True)),
                ('res_prof_self_development', models.IntegerField(blank=True, null=True)),
                ('res_prof_communication', models.IntegerField(blank=True, null=True)),
                ('res_stud', models.ForeignKey(db_column='res_stud', on_delete=django.db.models.deletion.CASCADE, to='portrait.students')),
            ],
            options={
                'db_table': 'results',
            },
        ),
    ]
