# Generated by Django 5.2.7 on 2026-06-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academicperformances',
            fields=[
                ('perf_id', models.AutoField(primary_key=True, serialize=False)),
                ('perf_year', models.CharField(max_length=16)),
                ('perf_current', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('perf_digital', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('perf_main', models.IntegerField(blank=True, null=True)),
                ('perf_first_retake', models.IntegerField(blank=True, null=True)),
                ('perf_second_retake', models.IntegerField(blank=True, null=True)),
                ('perf_grade_retake', models.IntegerField(blank=True, null=True)),
                ('perf_final', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'academicperformances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competencecenters',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False)),
                ('center_name', models.TextField()),
            ],
            options={
                'db_table': 'competencecenters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courseresults',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_an_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_client_focus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_communication', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_leadership', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_result_orientation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_planning_org', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_rules_culture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_self_dev', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_collaboration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_stress_resistance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_emotions_communication', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_negotiations', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_digital_comm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_effective_learning', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_entrepreneurship', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_creativity_tech', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_trendwatching', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_conflict_management', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_career_management', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_burnout', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_cross_cultural_comm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_mentoring', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'courseresults',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datauploadtemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=256, unique=True)),
                ('template_description', models.TextField(blank=True, null=True)),
                ('template_config', models.JSONField()),
                ('template_created_at', models.DateTimeField(blank=True, null=True)),
                ('template_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datauploadtemplate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Educationdisciplines',
            fields=[
                ('edu_disc_id', models.AutoField(primary_key=True, serialize=False)),
                ('edu_disc_name', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'educationdisciplines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Educationforms',
            fields=[
                ('edu_form_id', models.AutoField(primary_key=True, serialize=False)),
                ('edu_form_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'educationforms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Educationlevels',
            fields=[
                ('edu_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('edu_level_name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'educationlevels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Educationspecialties',
            fields=[
                ('edu_spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('edu_spec_name', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'educationspecialties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('inst_id', models.AutoField(primary_key=True, serialize=False)),
                ('inst_name', models.TextField()),
            ],
            options={
                'db_table': 'institutions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_rsv', models.CharField(max_length=512, unique=True)),
                ('part_course_num', models.IntegerField(blank=True, null=True)),
                ('part_gender', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentmapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('mapping_rsv', models.CharField(max_length=512, unique=True)),
                ('mapping_stud_name', models.CharField(max_length=512)),
                ('mapping_stud_gender', models.IntegerField(blank=True, null=True)),
                ('mapping_email', models.CharField(blank=True, max_length=256, null=True)),
                ('mapping_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'studentmapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testresults',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_course', models.IntegerField(blank=True, null=True)),
                ('res_year', models.CharField(max_length=16)),
                ('res_potential', models.IntegerField(blank=True, null=True)),
                ('res_report', models.CharField(blank=True, max_length=1024, null=True)),
                ('res_comp_info_analysis', models.IntegerField(blank=True, null=True)),
                ('res_comp_planning', models.IntegerField(blank=True, null=True)),
                ('res_comp_result_orientation', models.IntegerField(blank=True, null=True)),
                ('res_comp_stress_resistance', models.IntegerField(blank=True, null=True)),
                ('res_comp_partnership', models.IntegerField(blank=True, null=True)),
                ('res_comp_rules_compliance', models.IntegerField(blank=True, null=True)),
                ('res_comp_self_development', models.IntegerField(blank=True, null=True)),
                ('res_comp_leadership', models.IntegerField(blank=True, null=True)),
                ('res_comp_emotional_intel', models.IntegerField(blank=True, null=True)),
                ('res_comp_client_focus', models.IntegerField(blank=True, null=True)),
                ('res_comp_communication', models.IntegerField(blank=True, null=True)),
                ('res_comp_passive_vocab', models.IntegerField(blank=True, null=True)),
                ('res_mot_autonomy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_altruism', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_challenge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_career', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_creativity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_relationships', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_recognition', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_affiliation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_self_development', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_purpose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_cooperation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_stability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_tradition', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_management', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_mot_work_conditions', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('res_val_honesty_justice', models.IntegerField(blank=True, null=True)),
                ('res_val_humanism', models.IntegerField(blank=True, null=True)),
                ('res_val_patriotism', models.IntegerField(blank=True, null=True)),
                ('res_val_family', models.IntegerField(blank=True, null=True)),
                ('res_val_health', models.IntegerField(blank=True, null=True)),
                ('res_val_environment', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'testresults',
                'managed': False,
            },
        ),
    ]
